-- AlterTable
ALTER TABLE `sessoes_presenca`
  ADD COLUMN `tipo` ENUM('AULA', 'TESTE') NOT NULL DEFAULT 'AULA',
  ADD COLUMN `horaInicio` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `toleranciaMinutos` INTEGER NOT NULL DEFAULT 15,
  ADD COLUMN `limiteEntradaMinutos` INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN `duracaoMinutos` INTEGER NULL;

-- AlterTable
ALTER TABLE `presencas_aula`
  ADD COLUMN `estado` ENUM('PRESENTE', 'ATRASADO', 'NAO_ADMITIDO') NOT NULL DEFAULT 'PRESENTE',
  ADD COLUMN `minutosAtraso` INTEGER NOT NULL DEFAULT 0;
